// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICorePraktika.Data.DepartamentData;

namespace WebAPICorePraktika.Migrations
{
    [DbContext(typeof(DepartamentContext))]
    [Migration("20201022085356_PozicionPuneMigration")]
    partial class PozicionPuneMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPICorePraktika.Models.Departamenti", b =>
                {
                    b.Property<int>("DepartamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DepDataKrijimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartamentEmer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartamentPershkrimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentId");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("WebAPICorePraktika.Models.PozicioniPunes", b =>
                {
                    b.Property<int>("PozicionPuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<string>("PozicionPuneEmri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozicionPuneId");

                    b.HasIndex("DepartamentId");

                    b.ToTable("PozicioniPune");
                });

            modelBuilder.Entity("WebAPICorePraktika.Models.PozicioniPunes", b =>
                {
                    b.HasOne("WebAPICorePraktika.Models.Departamenti", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
